#!/bin/bash

# vulkaninfo --json always saves a file so we have to do this sadly...
vulkaninfo --json -o $SNAP_USER_COMMON/vkinfodump.json 
cat $SNAP_USER_COMMON/vkinfodump.json | jq .VkPhysicalDeviceProperties 2>&1> /dev/null
result=$?
rm $SNAP_USER_COMMON/vkinfodump.json

exit $result
